#!/usr/bin/env python3
"""Convert one basic CWCheat entry into a PSP Lua Mod Manager mod."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path


CHEAT_HEADER = re.compile(r"^_C([01])\s+(.+?)\s*$", re.IGNORECASE)
CODE_LINE = re.compile(
    r"^_L\s+(?:0x)?([0-9a-fA-F]{8})\s+(?:0x)?([0-9a-fA-F]{8})(?:\s|$)",
    re.IGNORECASE,
)
PSP_RAM_BASE = 0x08800000
PSP_RAM_END = 0x0A000000


@dataclass
class Cheat:
    name: str
    initially_enabled: bool
    lines: list[tuple[int, int, int]]


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")
    return slug or "converted_cheat"


def parse_cheats(path: Path) -> list[Cheat]:
    cheats: list[Cheat] = []
    current: Cheat | None = None
    for line_number, raw in enumerate(path.read_text(encoding="utf-8-sig", errors="replace").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("//") or line.startswith("#") or line.startswith("_S") or line.startswith("_G"):
            continue
        header = CHEAT_HEADER.match(line)
        if header:
            current = Cheat(header.group(2), header.group(1) == "1", [])
            cheats.append(current)
            continue
        code = CODE_LINE.match(line)
        if code:
            if current is None:
                raise ValueError(f"line {line_number}: _L found before a _C0/_C1 header")
            first, second = int(code.group(1), 16), int(code.group(2), 16)
            code_type = first >> 28
            if code_type not in (0, 1, 2):
                raise ValueError(
                    f"line {line_number}: unsupported CWCheat type 0x{code_type:X} "
                    f"({first:08X} {second:08X}); only constant 8/16/32-bit writes are supported"
                )
            width = {0: 8, 1: 16, 2: 32}[code_type]
            address = PSP_RAM_BASE + (first & 0x0FFFFFFF)
            if address < PSP_RAM_BASE or address + width // 8 > PSP_RAM_END:
                raise ValueError(f"line {line_number}: converted address 0x{address:08X} is outside PSP game RAM")
            value_mask = {8: 0xFF, 16: 0xFFFF, 32: 0xFFFFFFFF}[width]
            current.lines.append((width, address, second & value_mask))
            continue
        if line.startswith("_"):
            raise ValueError(f"line {line_number}: unrecognized directive: {line}")
    return [cheat for cheat in cheats if cheat.lines]


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_mod(cheat: Cheat, mod_id: str, display_name: str, game_id: str) -> str:
    patches = "\n".join(
        f"    {{{width}, 0x{address:08X}, 0x{value:0{width // 4}X}}},"
        for width, address, value in cheat.lines
    )
    return f'''-- Generated by cwcheat_to_mod.py. Review before using on real hardware.
local id = {lua_string(mod_id)}
local supported = system.game_id() == {lua_string(game_id)}
local enabled = mods.is_active(id)
local message = ""
local originals = {{}}

local patches = {{
{patches}
}}

local function key(width, address)
    return tostring(width) .. ":" .. tostring(address)
end

local function read_value(width, address)
    if width == 8 then return memory.read8(address) end
    if width == 16 then return memory.read16(address) end
    return memory.read32(address)
end

local function write_patch(patch, remember)
    local width, address, value = patch[1], patch[2], patch[3]
    local patch_key = key(width, address)
    if remember and originals[patch_key] == nil then
        originals[patch_key] = read_value(width, address)
    end
    if width == 8 then memory.write8(address, value)
    elseif width == 16 then memory.write16(address, value)
    else mods.hook32(id, address, value, originals[patch_key]) end
end

local mod = {{
    id = id,
    name = {lua_string(display_name)},
    game = supported and {lua_string(game_id)} or "UNSUPPORTED GAME"
}}

function mod.is_enabled() return enabled end
function mod.status() return message end

function mod.enable()
    if not supported then error("unsupported game: " .. tostring(system.game_id())) end
    for _, patch in ipairs(patches) do write_patch(patch, true) end
    enabled = true
    message = "MOD ENABLED"
end

function mod.disable()
    mods.disable(id)
    for _, patch in ipairs(patches) do
        local width, address = patch[1], patch[2]
        if width ~= 32 then
            local original = originals[key(width, address)]
            if original ~= nil then
                if width == 8 then memory.write8(address, original)
                else memory.write16(address, original) end
            end
        end
    end
    enabled = false
    message = "MOD DISABLED"
end

function mod.update()
    if enabled then
        for _, patch in ipairs(patches) do write_patch(patch, false) end
    end
end

return mod
'''


def choose_cheat(cheats: list[Cheat], requested: str | None) -> Cheat:
    if not cheats:
        raise ValueError("no non-empty _C0/_C1 cheat entries were found")
    if requested is not None:
        exact = [item for item in cheats if item.name.casefold() == requested.casefold()]
        if len(exact) != 1:
            names = ", ".join(item.name for item in cheats)
            raise ValueError(f"cheat {requested!r} was not found; available entries: {names}")
        return exact[0]
    if len(cheats) != 1:
        names = "\n".join(f"  - {item.name}" for item in cheats)
        raise ValueError(f"the input contains multiple cheats; select one with --cheat:\n{names}")
    return cheats[0]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="CWCheat text file")
    parser.add_argument("output", type=Path, help="output mod directory")
    parser.add_argument("--game-id", required=True, help="target game ID, for example ULJM05500")
    parser.add_argument("--cheat", help="exact _C0/_C1 name when the input contains multiple entries")
    parser.add_argument("--id", dest="mod_id", help="mod ID; defaults to a slug of the cheat name")
    parser.add_argument("--name", help="display name; defaults to the CWCheat entry name")
    parser.add_argument("--force", action="store_true", help="replace an existing output directory")
    args = parser.parse_args()

    try:
        cheat = choose_cheat(parse_cheats(args.input), args.cheat)
        mod_id = args.mod_id or slugify(cheat.name)
        if not re.fullmatch(r"[a-z0-9_]+", mod_id):
            raise ValueError("mod ID may contain only lowercase letters, digits, and underscores")
        game_id = args.game_id.upper().replace("-", "")
        if not re.fullmatch(r"[A-Z]{4}[0-9]{5}", game_id):
            raise ValueError("game ID must look like ULJM05500 or ULUS10391")
        if args.output.exists():
            if not args.force:
                raise ValueError(f"output already exists: {args.output} (use --force to replace it)")
            if args.output.is_dir():
                shutil.rmtree(args.output)
            else:
                args.output.unlink()
        args.output.mkdir(parents=True)
        (args.output / "mod.lua").write_text(
            render_mod(cheat, mod_id, args.name or cheat.name, game_id), encoding="utf-8"
        )
        (args.output / "README.txt").write_text(
            "Generated from a CWCheat entry.\n"
            "Supported conversion: constant 8-bit, 16-bit, and 32-bit writes.\n"
            "Review addresses and test in PPSSPP before using on a real PSP.\n",
            encoding="utf-8",
        )
    except (OSError, ValueError) as error:
        parser.error(str(error))
    print(f"Created {args.output / 'mod.lua'} with {len(cheat.lines)} patches.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
